include: ["_pages"]

email: test@test.com
desicption: test
baseurl: "/space-robotics-rss" # the subpath of your site, e.g. /blog
url: "https://albee.github.io"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "default" #, "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# teaser: /assets/images/albee_astrobee.png
# logo: /assets/images/albee_astrobee.png

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

atom_feed:
  hide: true