include: ["_pages"]

title: "RSS 2025: Space Robotics Workshop"
email: test@test.com
desicption: test
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://albee.github.io"

# Build settings
baseurl: ""
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

minimal_mistakes_skin: "" #, "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# teaser: /assets/images/albee_astrobee.png
# logo: /assets/images/albee_astrobee.png
masthead_title: "RSS 2025: Space Robotics Workshop"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      custom_stylesheet: assets/css/custom.css

atom_feed:
  hide: true